const fs = require('fs');
let s = fs.readFileSync('script.js', 'utf8').replace(/\r\n/g, '\n');

// ASTEROIDS SPRITES
const beltOld = "function buildAsteroidBelt() {\n  const count = 4000;\n  const rockGeo = createRockGeometry();\n  const rockMat = new THREE.MeshPhongMaterial({ color: 0x998877, shininess: 5 });\n  const mesh = new THREE.InstancedMesh(rockGeo, rockMat, count);\n  const dummy = new THREE.Object3D();\n  for (let i = 0; i < count; i++) {\n    const r = 43 + Math.random() * 8;\n    const a = Math.random() * Math.PI * 2;\n    const y = (Math.random() - 0.5) * 1.5;\n    dummy.position.set(Math.cos(a) * r, y, Math.sin(a) * r);\n    dummy.rotation.set(Math.random() * Math.PI, Math.random() * Math.PI, Math.random() * Math.PI);\n    const s = 0.2 + Math.random() * 1.8;\n    dummy.scale.set(s, s, s);\n    dummy.updateMatrix();\n    mesh.setMatrixAt(i, dummy.matrix);\n  }\n  mesh.instanceMatrix.needsUpdate = true;\n  scene.add(mesh);\n}";
const beltNew = "function buildAsteroidBelt() {\n  const count = 4000;\n  const tex = new THREE.TextureLoader().load('img/textures/asteroide.png');\n  const mat = new THREE.SpriteMaterial({ map: tex });\n  const group = new THREE.Group();\n  for (let i = 0; i < count; i++) {\n    const sprite = new THREE.Sprite(mat);\n    const r = 43 + Math.random() * 8;\n    const a = Math.random() * Math.PI * 2;\n    const y = (Math.random() - 0.5) * 1.5;\n    sprite.position.set(Math.cos(a) * r, y, Math.sin(a) * r);\n    const s = 0.4 + Math.random() * 1.8;\n    sprite.scale.set(s, s, s);\n    group.add(sprite);\n  }\n  scene.add(group);\n}";
s = s.replace(beltOld, beltNew);

const kuiperOld = "function buildKuiperBelt() {\n  const count = 4000;\n  const rockGeo = createRockGeometry();\n  const rockMat = new THREE.MeshPhongMaterial({ color: 0x667788, shininess: 3 });\n  const mesh = new THREE.InstancedMesh(rockGeo, rockMat, count);\n  const dummy = new THREE.Object3D();\n  for (let i = 0; i < count; i++) {\n    const r = 122 + Math.random() * 18;\n    const a = Math.random() * Math.PI * 2;\n    const y = (Math.random() - 0.5) * 4;\n    dummy.position.set(Math.cos(a) * r, y, Math.sin(a) * r);\n    dummy.rotation.set(Math.random() * Math.PI, Math.random() * Math.PI, Math.random() * Math.PI);\n    const s = 0.15 + Math.random() * 2.0;\n    dummy.scale.set(s, s, s);\n    dummy.updateMatrix();\n    mesh.setMatrixAt(i, dummy.matrix);\n  }\n  mesh.instanceMatrix.needsUpdate = true;\n  scene.add(mesh);\n}";
const kuiperNew = "function buildKuiperBelt() {\n  const count = 4000;\n  const tex = new THREE.TextureLoader().load('img/textures/asteroide.png');\n  const mat = new THREE.SpriteMaterial({ map: tex });\n  const group = new THREE.Group();\n  for (let i = 0; i < count; i++) {\n    const sprite = new THREE.Sprite(mat);\n    const r = 122 + Math.random() * 18;\n    const a = Math.random() * Math.PI * 2;\n    const y = (Math.random() - 0.5) * 4;\n    sprite.position.set(Math.cos(a) * r, y, Math.sin(a) * r);\n    const s = 0.3 + Math.random() * 2.0;\n    sprite.scale.set(s, s, s);\n    group.add(sprite);\n  }\n  scene.add(group);\n}";
s = s.replace(kuiperOld, kuiperNew);

const groupOld = "function buildAsteroidGroup() {\n  asteroidGroup = new THREE.Group();\n\n  const asteroidColors = [0x6b6b7b, 0x7a7062, 0x5e5e6e, 0x8a7e6b, 0x4a4a5a];\n\n  for (let i = 0; i < 25; i++) {\n    const size = 0.15 + Math.random() * 0.5;\n    const geo = new THREE.IcosahedronGeometry(size, 1);\n    const posAttr = geo.getAttribute('position');\n    for (let j = 0; j < posAttr.count; j++) {\n      const x = posAttr.getX(j);\n      const y = posAttr.getY(j);\n      const z = posAttr.getZ(j);\n      const noise = 0.7 + Math.random() * 0.6;\n      posAttr.setXYZ(j, x * noise, y * noise, z * noise);\n    }\n    posAttr.needsUpdate = true;\n    geo.computeVertexNormals();\n    const mat = new THREE.MeshStandardMaterial({\n      color: asteroidColors[Math.floor(Math.random() * asteroidColors.length)],\n      roughness: 0.9 + Math.random() * 0.1,\n      metalness: Math.random() * 0.15,\n      flatShading: true,\n    });\n    const mesh = new THREE.Mesh(geo, mat);\n    const orbitAngle = Math.random() * Math.PI * 2;\n    const orbitRadius = 80 + (Math.random() - 0.5) * 12;\n    const orbitInclination = 0.4 + (Math.random() - 0.5) * 0.15;\n    mesh.position.x = Math.cos(orbitAngle) * orbitRadius;\n    mesh.position.z = Math.sin(orbitAngle) * orbitRadius;\n    mesh.position.y = Math.sin(orbitAngle * 0.7) * orbitRadius * orbitInclination;\n    mesh.rotation.set(Math.random() * Math.PI, Math.random() * Math.PI, Math.random() * Math.PI);\n    mesh.userData = {\n      orbitAngle,\n      orbitRadius,\n      orbitInclination,\n      rotSpeed: (Math.random() - 0.5) * 0.02,\n      orbitSpeed: 0.002 + (Math.random() - 0.5) * 0.0008,\n    };\n    asteroidGroup.add(mesh);\n  }";
const groupNew = "function buildAsteroidGroup() {\n  asteroidGroup = new THREE.Group();\n\n  const tex = new THREE.TextureLoader().load('img/textures/asteroide.png');\n  const mat = new THREE.SpriteMaterial({ map: tex });\n\n  for (let i = 0; i < 25; i++) {\n    const size = 0.5 + Math.random() * 1.5;\n    const mesh = new THREE.Sprite(mat);\n    mesh.scale.set(size, size, size);\n\n    const orbitAngle = Math.random() * Math.PI * 2;\n    const orbitRadius = 80 + (Math.random() - 0.5) * 12;\n    const orbitInclination = 0.4 + (Math.random() - 0.5) * 0.15;\n    mesh.position.x = Math.cos(orbitAngle) * orbitRadius;\n    mesh.position.z = Math.sin(orbitAngle) * orbitRadius;\n    mesh.position.y = Math.sin(orbitAngle * 0.7) * orbitRadius * orbitInclination;\n    mesh.userData = {\n      orbitAngle,\n      orbitRadius,\n      orbitInclination,\n      rotSpeed: 0,\n      orbitSpeed: 0.002 + (Math.random() - 0.5) * 0.0008,\n    };\n    asteroidGroup.add(mesh);\n  }";
s = s.replace(groupOld, groupNew);

// Restore CRLF for windows
s = s.replace(/\n/g, '\r\n');

fs.writeFileSync('script.js', s, 'utf8');
